### ISSUE TITLE
Remember new tab page

### ISSUE THREAD

**Issue by Gi11i4m** [jimschubert/NewTab-Redirect#101]
Not sure if this is a good idea, but I think it would be handy if this extension could have an option to remember the page you left it on.

For example, I set the chrome bookmark manager as new tab page, but if I go into a folder, I'd like it to go to that folder next time I open a new tab. Maybe this could be achieved by saving the new url somewhere (or just updating the redirect url) for as long as you stay in the same domain?

I could see benefits in this even when using a website as new tab page. If you set reddit as your new tab page, it could be nice if the article or subreddit you were on was opened again next time. Or with Google Drive or Dropbox the folder you were in.

**Comment by jimschubert** [comment]
Hi, thanks for submitting this feature request.

Unfortunately, this isn't something that New Tab Redirect can do. 

In order to do this, it would require more permissions to allow a 'content script' to be injected into every page you visit. That script would then have to save the current URL back to the extension. If done improperly, this would mean that any malicious or infected site could then programmatically set the URL that will load the next time you open a new tab. Although the feature isn't a security issue in itself, I don't trust JavaScript *that much* so it's not a feature I'm comfortable with adding since it would result in a lot of backlash from the extensions' 500,000+ users.

Aside from the concern about users not wanting such functionality and the security risks inherent with allowing javascript on any page to set your current location, the state of the web poses some technical limitations. Pages are no longer one-file-per-page static sites or even one dynamic location per page (like reddit). There are now millions of single page applications (like the chrome://bookmarks page) which may require some state prior to reaching the page you're on and there's no guarantee that navigating to that page will result in the same view of the page from your previous visit. This concept is called [deep linking](http://www.wikiwand.com/en/Deep_linking) and sadly not every site supports it.

This would be an interesting experiment as a separate extension, I just don't have time to play around with it. One *could* attempt to reconcile the issues discussed above and simply reload the last visited page when you direct to the root of a web site. However, take this page for example. If you last visited `https://github.com/jimschubert/NewTab-Redirect/issues/101` and I linked you in an email to another issue like `https://github.com/jimschubert/NewTab-Redirect/issues/55`, when that page loaded you wouldn't want to be redirected to this page because it was the last one you visited. What if you only wanted to redirect to `https://github.com/jimschubert/NewTab-Redirect/issues/101` if you visited the nested route `https://github.com/jimschubert/NewTab-Redirect` but not `github.com` or `github.com/jimschubert`?

Working out the complexities of user navigation *across the web* may be too much. It's a cool idea, though. You could try posting to the [Google Chrome Forum](https://productforums.google.com/forum/#!forum/chrome) and see if there are any existing extensions out there. I got the idea for this extension from someone's random post on a forum.

**Comment by Gi11i4m** [comment]
Thank you for the fast and thorough reply! I see the security risks, and if
you indeed have half a million customers it's good that you think about new
features in this way!

For the dynamic pages, you're partly right, but well made dynamic pages do
use unique urls for everys page as well, so you can get to a specific
folder in the chrome://bookmarks page just by remembering the url. But for
a lot of pages this would indeed not work correctly.

And yeah, maybe I'll post it in the Google Chrome Forum, thanks for the
tip! Or maybe if I'm done studying I'll try to implement it in this
extension and see if it was actually a good idea :D.

Good luck with all your future development!

Greetings,
Gilliam

Op do 12 mrt. 2015 om 01:25 schreef Jim Schubert <notifications@github.com>:
