### ISSUE TITLE
Has this ever happened to anyone? When you put C:/blah blah it deletes the (:) for some reason.

### ISSUE THREAD

**Issue by Buttass96** [jimschubert/NewTab-Redirect#116]
![what tf](https://cloud.githubusercontent.com/assets/17134839/12906677/c4d174d4-ceb0-11e5-9969-4a934e10e178.gif)

please tell me you can see this gif

**Comment by inexist3nce** [comment]
Use the file protocol: `file:///C:/Users/Jovan/Desktop/Categories-Anon`.

**Comment by jimschubert** [comment]
@inexist3nce is correct. 

When you put only C:/, I believe that's considered an authentication part of a local network path. You'd have to specify file:, just like web links are http:.  The reason you can navigate to a web link without specifying http:// in the browser is because that's the default protocol.
