### ISSUE TITLE
Problem with Chromebook with NewTab-Redirect

### ISSUE THREAD

**Issue by lesgit** [jimschubert/NewTab-Redirect#124]
I use both a macbook pro and a toshiba chromebook 2. I have noticed that when I use the mac and have chrome://apps/ in the redirect url it works perfectly. However with the chromebook I get an error message "site not found" with exactly the same chrome://apps/ in the redirect url.

Can you help me with this?

Thanks,
Les

**Comment by jimschubert** [comment]
Hi Les. If you navigate to chrome://chrome-urls do you see apps there?  I don't have a Chromebook to investigate.

**Comment by kpearsonxyz** [comment]
Because the Chromebook uses all the apps find in chrome://apps it doesn't allow using it in the URL field.
If we can use chrome://chrome-urls on a Chromebook that would be awesome. I'll check that when I can...
Jim, could you add that as an option we can choose with, or instead of apps?
For one iteration of either this extension or Chromebook's version, this extension worked the same on both, then it just went back to not working with the message, "site not found"...

**Comment by jimschubert** [comment]
@kpearsonxyz I've just seen your response on this old issue. I don't really "add" support for URLs to this extension, they either work or they don't.

**Comment by kpearsonxyz** [comment]
Fair enough.



---
Karl L. Pearson | karlplds@gmail.com
Pardon brevity or typos. Sent from my phone.
---
