### ISSUE TITLE
Popular pages

### ISSUE THREAD

**Issue by dbox** [jimschubert/NewTab-Redirect#126]
Hey Jim-

Love your extension. Thanks so much for making it.

Was wondering if you'd consider adding http://myfav.es to the list of popular sites. It's a handy start page that works perfectly in tandem with your extension.

Happy to attempt a PR for this. Thanksa!

**Comment by jimschubert** [comment]
@dbox thanks for the suggestion. I pulled the list of sites from the Alexa top websites list back in 2009 or 2010. Because I don't plan to promote third party sites, add advertising or data collection mechanisms, I won't be adding sites to the popular pages.

I'd previously considered "partnerships" in this way, but it would result in too much effort and responsibility on my part for the safety of my users. Sticking with big name sites with hundreds of millions of users removes me from some of that headache.

I like your site, though. If you tweet me at jimschubert and mention the site along with New Tab Redirect I will gladly retweet. I know it's not the same thing, though.

**Comment by dbox** [comment]
No worries. Thanks!
