### ISSUE TITLE
Defect: "New Tab Redirect" Extension in Chrome Opens an Unprompted New Tab/Window 

### ISSUE THREAD

**Issue by keauser** [jimschubert/NewTab-Redirect#133]
While performing normal activity or simply having a window open (without using the keyboard or mouse), "New Tab Redirect" will open a new tab or window without any user action being taken. Uninstalling and reinstalling the extension did not correct the problem - neither did changing any of the settings. (options).

**Comment by EnejBu** [comment]
Hi! I have the same problem as you. Did you manage to solve the problem? I would appreciate any suggestions, because I already try a few things and it didn't work.

**Comment by jimschubert** [comment]
Sorry, I haven't reproduced the issue.

New Tab Redirect doesn't open new tabs unless you're on the custom apps page, have enabled the `tabs` permission, and you've clicked the icon for opening an app in a new tab. 

Google Chrome provides an extension type for override pages called `newtab`. It handles everything, from opening new tabs to invoking the new tab override extension. My extension literally did nothing until it has already been loaded into that new page, and once it has displayed the custom URL or built-in apps page it leaves memory.

If a new tab is opening randomly, it would be a bug in chrome or perhaps another extension trying to open a new tab. I'd recommend reporting the bug to Chrome, because it could be a known issue there.
