### ISSUE TITLE
 Always update tab option not working in chrome 61

### ISSUE THREAD

**Issue by godey4me** [jimschubert/NewTab-Redirect#140]
Hi,
Chromes update 61 broke something. The " Always update tab, not redirect. (Enable for cursor in the address bar)" option does not work anymore.
Experience on Windows 10 and Win 7.

**Comment by jacekkopecky** [comment]
Same here, MacOs Sierra. Happy to try and debug if you tell me how – no experience with authoring extensions yet.

**Comment by jacekkopecky** [comment]
Well I couldn't find a way for an extension to change this behaviour, must be new new-tab or `chrome.tabs.update` behaviour in chrome.

**Comment by jimschubert** [comment]
Sorry I didn't see this yesterday.

Yeah the option and that functionality in general is a crapshoot. It has to do with the browser's threading. Because pages are handled on one thread while browser operations are handled on another, you can sometimes "trick" the browser into switching in time.

Sorry, there's not much more that can be done to resolve the issue.

**Comment by jacekkopecky** [comment]
Well I've solved it for myself: made a new extension (from NewTab-Redirect, thanks) that basically has my desired own page instead of `main.html`. Now my page shows up in any new tab, and the address bar is empty so I can start typing.

If anybody needs more info or a step-by-step, let me know.

**Comment by jimschubert** [comment]
@jacekkopecky If you don't need the options from this extension (which is the whole point of the extension), you're just creating a simple redirect extension.  All you'll need is manifest.json and the HTML file. I have an example which redirects to duckduckgo here: https://github.com/jimschubert/duckduckgo-newtab. Even as simple as that extension is, and redirect mechanism will lose address bar focus. Coding an html file with no redirect will focus the address bar because the browser doesn't have to switch to the sandbox that renders web pages.

**Comment by godey4me** [comment]
@jacekkopecky. Please share your step by step guide for us to follow.
Thanks

**Comment by jacekkopecky** [comment]
Thanks @jimschubert , that's very helpful actually!

@godey4me check out [this gist](https://gist.github.com/jacekkopecky/410872d6fee9b7632e7a5cafade4f199)

**Comment by godey4me** [comment]
Thanks! @jacekkopecky I will take a look.

**Comment by SlavikCA** [comment]
Looks like issue is going to be fixed in Chrome 62, as said here:
https://bugs.chromium.org/p/chromium/issues/detail?id=752794

> The fix (mentioned in c#2) landed in M62

**Comment by jimschubert** [comment]
To clarify...the linked issue doesn't apply fully to New Tab Redirect. If New Tab Redirect was a hard coded URL, it would apply. Since this extension redirects to a _user specified_ URL, the behavior is a crapshoot. It's a mix of race conditions in threading and Chrome memory usage.

If this was the behavior you experienced previously, hopefully it will be fixed. If you didn't experience this behavior before, don't bank on the big fixing this.
