### ISSUE TITLE
Local Security Authority Process

### ISSUE THREAD

**Issue by BobStolp** [jimschubert/NewTab-Redirect#147]
Windows 10.  Chrome 62.0.3202.94 (Official Build) (64-bit)... After installing the New Tab Redirect extension...,  The first time I open Chrome it starts quickly, but my Local Security Authority Process goes to 30% CPU.  If I continue to open Chrome windows they open quickly, but the Local Security Authority Process stays at 30%. Once I shut down all Chrome sessions, the Local Security Authority Process stays at 30% and opening the next Chrome session takes about 45 seconds.  I notice that although I have shutdown all previous Chrome sessions, they remain running Processes in Task Manager and dont really shutdown.  If I go kill them in Task Manager, the LSAP goes away and the next Chrome session starts in about a second.  I have tried to remove the extension, but it hasn't helped.  I have cleared cache and rebooted several times.

**Comment by jimschubert** [comment]
Unfortunately, this is outside the scope and control of extensions.

Extensions may only interact with Chrome through a small set of interfaces, none of which know about Windows processes. The extension uses Google Account sync to store settings, but this is managed by the browser and not the extension. If Google Account sync is causing the problem, you could disable this extension and install another that is account sync (I think Google Hangouts does) to see if your issue is consistent. If it is, and you're concerned about the usage, you'll want to file a bug with Google Chrome.
