### ISSUE TITLE
Feature request - add a checkbox to "not redirect new tab, if the page is already opened in another tab"

### ISSUE THREAD

**Issue by vitaliyhayda** [jimschubert/NewTab-Redirect#182]
**Feature request**:
Add a checkbox to "not redirect new tab, if the page is already opened in another tab"

For some reason, I keep finding myself having 3-4 of the same "redirected new tabs" after a few hours of use ¯\_(ツ)_/¯ 

Totally my fault, but this checkbox (across same browser window) will definitely help.

**Comment by jimschubert** [comment]
Adding such a check isn't really viable, unfortunately. It would require iterating over all tabs and evaluating the addresses, which is a very slow process (even on my beefy machine it can take 1s or longer with the number of tabs I regularly keep). I'm in the same boat as you, though, as I end up with multiple similar tabs open.

I'd recommend adding another extension which manages duplicate tabs. I know it's not ideal, but implementing it in this extension would be slow and clunky.

I personally use [Vimium](https://chrome.google.com/webstore/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb) which allows for tab management using vim-like hotkeys. I use the <kbd>SHIFT</kbd><kbd>T</kbd> feature hundreds of times a day… it allows you to search through your currently active tabs and quickly navigate to them. It's nice because it will display most recent tab so you can easily jump back and forth between non-adjacent tabs. And, the search feature searches the URL as well as the page title. Here's an example:

![image](https://user-images.githubusercontent.com/109659/93413208-be3c4a00-f86c-11ea-86f5-3b63474c5c58.png)
