### ISSUE TITLE
Cannot set non-URL as new tab

### ISSUE THREAD

**Issue by KeronCyst** [jimschubert/NewTab-Redirect#184]
I want to set this as my new tab but it's not doing it:

`data:text/html, <title>Jot</title><body text="lightgray" contenteditable style="border: 10px ridge darkgray; background: darkslategray; font-size: 2rem; line-height: 1.4; max-width: 75rem; margin:10 auto; padding: 1rem;">Text/Images`

**Comment by jimschubert** [comment]
This isn't supported by Chrome, so nothing I can really do about it.

I'd recommend creating a local HTML file, or even better creating your own new tab redirect override page as you'll get address bar highlighting which isn't possible in NTR due to the redirecting nature. For steps how to create the custom extension, see my comment at https://github.com/jimschubert/NewTab-Redirect/issues/166#issuecomment-501093513
