### ISSUE TITLE
the new tab has changed over the last few days

### ISSUE THREAD

**Issue by alemly** [jimschubert/NewTab-Redirect#214]
greetings - been using the new tab extension for so many years

a few days ago it changed: now it comes with a black background - and worst of all: the order of the various links I've put on the tab have reversed!!! its quite confusing

is there a way to re-order things?

**Comment by RemcoScheffer** [comment]
Same issue since today. (01-07-2023)

**Comment by jimschubert** [comment]
NTR has not changed visually for almost 10 years.
You'll need to go through your extensions to find any other extension which overrides the new tab page to resolve.

**Comment by donbuelke** [comment]
Thanks for your response; however, as I've tried before, turning off all my
extensions except NTR didn't work. I shut down Chrome, then shut down and
restarted my computer to ensure I was getting a fresh start. On startup and
when a new tab is opened, it still presents that black screen with the web
apps invitation. I've re-downloaded the theme. I suspect the problem is
with Chrome/Google, or maybe my computer has become corrupted, although I'm
not having any other issues. I don't understand the use of web apps or how
it works.
