### ISSUE TITLE
Local file stopped working on Brave 1.59.117

### ISSUE THREAD

**Issue by serpro69** [jimschubert/NewTab-Redirect#221]
After upgrading brave-browser from 1.57.64 to 1.59.117, the extension no longer opens up the local file on new tab, instead just opens a blank page.
Downgrading brave fixes the issue, so it's something they "broke" or "restricted" in one of later versions that probably needs to be accounted for on the extension side of things?

OS Info: 
```
$ lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

$ uname -sr
Linux 6.2.0-34-generic
```

**Comment by serpro69** [comment]
Could be related to https://github.com/jimschubert/NewTab-Redirect/issues/218 ?

**Comment by jimschubert** [comment]
Chrome introduced a new option for local file access. I assume the same option exists on Brave which is based on Chromium. See the screenshot in #222.

It's definitely related to #218 because to resolve that issue, the extension had to be updated to Manifest v3 since they no longer allow publishing of v2.

**Comment by jimschubert** [comment]
see https://github.com/jimschubert/NewTab-Redirect/blob/master/README.md#missing-local-files
