### ISSUE TITLE
False positive with AdwCleaner malware removal tool

### ISSUE THREAD

**Issue by SnowGabe** [jimschubert/NewTab-Redirect#99]
AdwCleaner constantly finds malware in the New Tab Redirect folder. The extension is broken in the process.
I will attach a log to this message.

```
-AdwCleaner v4.111 - Logfile created 19/02/2015 at 03:46:04
-Updated 18/02/2015 by Xplode
-Database : 2015-02-18.3 [Server]
-Operating system : Windows 8.1  (x64)
-Username :
-Running from : C:\Users\User\Documents\adwcleaner_4.111.exe
-Option : Cleaning

***** [ Services ] *****


***** [ Files / Folders ] *****

Folder Deleted : C:\Users\User\AppData\Local\Google\Chrome\User Data\Default\Extensions\icpgjfneehieebagbmdbhnlpiopdcmna
File Deleted : C:\Users\User\AppData\Local\Google\Chrome\User Data\Default\Local Storage\hxxps_static.olark.com_0.localstorage-journal
File Deleted : C:\Users\User\AppData\Local\Google\Chrome\User Data\Default\Local Storage\hxxps_static.olark.com_0.localstorage
```

**Comment by SnowGabe** [comment]
How do I disable styles?!

**Comment by jimschubert** [comment]
Thanks for reporting this. The extension doesn't contain any malware, so I'm not sure why adw would delete the extension folder.  I googled the file `hxxps_static.olark.com_0.localstorage` and it  appears to be some virus that adds this file to Local Storage folders under Chrome's directory.

Unfortunately, there's nothing I can do about this. The extension doesn't have permissions to read or write to directories on your machine. The permissions the extension has don't allow for external processes to perform any sort of remote code execution through the extension. The only way for unwanted files like this to get into the extension directory is for some process outside of Chrome to add them.

If you don't have antivirus software, I'd suggest running a free program (I think AVG is still active and free). If you do have antivirus, check that the virus definitions are up to date.

As for how that file can be considered a virus, I'm not entirely sure. Google search showed a lot of valid applications and extensions being removed or flagged by AdwCleaner because of the same file. The only thing I could think of is if an extension blindly iterates over keys in localStorage looking for a URL or something and navigating to an infected site, there may be a possible security concern there. I'm not familiar enough with the browser's implementation of localStorage to comment anymore than speculation. I only use localStorage through google's chrome.storage API, so I would expect any vulnerabilities in HTML localStorage to be invalid in the extension.  I don't many extensions use the newer storage API though.

I will reach out to Adw and see if I can get information about the specific rule on that file so I can understand what they're blocking.

If your second part is asking about the post's formatting, you can put triple ticks (`) before and after your block of text to maintain the original formatting without special styles applied.

**Comment by SnowGabe** [comment]
I have Bitdefender Total Security 2015. Active protection is on. I have blocked both Java and Flash in my browsers. I always scan the files I download and I use WOT to measure if a website is safe to use.
I don't understand how malware always gets to my browser folder.

**Comment by jimschubert** [comment]
Malware is nasty. I don't really have to deal with it because I use Mac... I'm not invincible, it's just that most of the jerks that make malware do so for Windows (90%+ of users).

When I did use Windows, I ran SpyBot. That app has an advanced feature to modify your hosts file (a Unix-based DNS resolution file) to reroute known malicious sites back to your own machine. For insurance,  somebadsite.com would have the IP defined as 127.0.0.1. This is a special IP which would direct the request to your own computer, causing a page not found or loading a locally running web site if you have a Web server running.

I looked for the contact information for AdwCleaner last night and, to be honest I would personally be afraid to install that application. There are a lot of articles about fake versions of the app designed specifically to distribute malware. Without a dedicated website for the app, I cont really say what the intended "official" installer is. I did find the change log for the most recent version, and I plan to email the contact in a bit.

**Comment by SnowGabe** [comment]
I know Spybot but is this review competent? 
http://www.pcmag.com/article2/0,2817,2412372,00.asp

**Comment by Walkman100** [comment]
> to be honest I would personally be afraid to install that application.

I know I'm being technical here, but it doesn't really "install" - it's a scanner that scans when you run it, and doesn't if you don't.

**Comment by jimschubert** [comment]
Some of the files I found were .msi installers. My point was that there's no official site, so I didn't know what application to download.  I really only trust things I can get through a reputable store or app delivery service.

The PC Magazine article looks good, there's one thing in it that annoys me though. *Malware* is a really loaded term, it's like referring to Chrome Extensions or phone apps all as "Software". I don't think SpyBot and PC use the term "malware" interchangeably. Spyware/Malware scanners are one set of tools and Antivirus scanners are another set of tools. That article seems to knock the free version of SpyBot for not finding viruses.

Anyway, it's been a while since I've used Windows on my personal machine. Even when I did run Windows, Ubuntu Linux was my main operating system. My advice on Windows antivirus software is in no way up-to-date, so you've done the right thing by doing some research. When I ran Windows, I used a combination of SpyBot's hosts file protection, AVG, and whatever Microsoft's protection was called. I don't think you can use just one suite of software and assume you're safe. There are literally hundreds of new viruses every day, even if you ran 3 antivirus suites you can only remain protected as often as your virus definitions are updated.  Some software runs known heuristics and common security exploit checks, but virus authors find new attack vectors all the time. I have Kaspersky on my machine at work and I assume it works, but I've never received warnings about viruses and I wouldn't know a virus existed unless it interfered with something I do regularly.

To make things even worse-- and I think it's wrong for companies to do this-- places like Google will notify others (usually competitors) of security holes which, if not fixed within a certain amount of time, get released publicly. https://code.google.com/p/google-security-research/issues/list

I did email the author of AdwCleaner, but I haven't received a response.

**Comment by SnowGabe** [comment]
This happened again. A third time. The log identical and the extension was broken again. 
I understand that this probably isn't your fault. 

This is probably a false positive. I installed New Tab Redirect instantly after "malware" removal and AdwCleaner still reports an issue in the extension folder.

**Comment by jimschubert** [comment]
Thanks for the follow up. I still haven't received a reply from the developer of AdwCleaner. I asked him to explain why it's a false positive and if there is anything I can do to prevent New Tab Redirect from creating this false positive. I also asked to have New Tab Redirect removed from the list of threats.

Have you tried running any other virus scanners or manually deleting the two files:

```
File Deleted : C:\Users\User\AppData\Local\Google\Chrome\User Data\Default\Local Storage\hxxps_static.olark.com_0.localstorage-journal
File Deleted : C:\Users\User\AppData\Local\Google\Chrome\User Data\Default\Local Storage\hxxps_static.olark.com_0.localstorage
```

**Comment by SnowGabe** [comment]
I have Bitdefender Total Security active.

**Comment by jimschubert** [comment]
Sorry, I don't know what else to say. If Bitdefender Total Security doesn't complain about whatever is triggering the problem in AdwCleaner, it's obviously an issue with AdwCleaner. There's no way for the extension to read *or* write to your hard drive, so there's no reason that I know of for AdwCleaner to complain about a Google Chrome extension.

**Comment by SnowGabe** [comment]
I might add that AdwCleaner is absolutely filled with false positives. Take a look at this: https://imgur.com/a/gnsmJ
I changed all of these settings myself. AdwCleaner wants to reset everything to defaults.
